import {
  mauve,
  mauveDark,
  blue,
  blueDark,
  red,
  redDark,
  green,
  greenDark,
  yellow,
  yellowDark,
} from '@radix-ui/colors'

export type CustomTheme = typeof lightTheme

export const lightTheme = {
  type: 'light',
  colors: {
    gray1: mauve.mauve1,
    gray2: mauve.mauve2,
    gray3: mauve.mauve3,
    gray4: mauve.mauve4,
    gray5: mauve.mauve5,
    gray6: mauve.mauve6,
    gray7: mauve.mauve7,
    gray8: mauve.mauve8,
    gray9: mauve.mauve9,
    gray10: mauve.mauve10,
    gray11: mauve.mauve11,
    gray12: mauve.mauve12,
    accentBase: blue.blue1,
    accentBgSubtle: blue.blue2,
    accentBg: blue.blue3,
    accentBgHover: blue.blue4,
    accentBgActive: blue.blue5,
    accentLine: blue.blue6,
    accentBorder: blue.blue7,
    accentBorderHover: blue.blue8,
    accentSolid: blue.blue9,
    accentSolidHover: blue.blue10,
    accentText: blue.blue11,
    accentTextContrast: blue.blue12,
    success1: green.green1,
    success2: green.green2,
    warning1: yellow.yellow1,
    warning2: yellow.yellow2,
    danger1: red.red1,
    danger2: red.red2,
  },
  breakpoints: {
    tablet: '768px',
    mobile: '425px',
  },
}

export const darkTheme = {
  type: 'dark',
  colors: {
    gray1: mauveDark.mauve1,
    gray2: mauveDark.mauve2,
    gray3: mauveDark.mauve3,
    gray4: mauveDark.mauve4,
    gray5: mauveDark.mauve5,
    gray6: mauveDark.mauve6,
    gray7: mauveDark.mauve7,
    gray8: mauveDark.mauve8,
    gray9: mauveDark.mauve9,
    gray10: mauveDark.mauve10,
    gray11: mauveDark.mauve11,
    gray12: mauveDark.mauve12,
    accentBase: blueDark.blue1,
    accentBgSubtle: blueDark.blue2,
    accentBg: blueDark.blue3,
    accentBgHover: blueDark.blue4,
    accentBgActive: blueDark.blue5,
    accentLine: blueDark.blue6,
    accentBorder: blueDark.blue7,
    accentBorderHover: blueDark.blue8,
    accentSolid: blueDark.blue9,
    accentSolidHover: blueDark.blue10,
    accentText: blueDark.blue11,
    accentTextContrast: blueDark.blue12,
    success1: greenDark.green1,
    success2: greenDark.green2,
    warning1: yellowDark.yellow1,
    warning2: yellowDark.yellow2,
    danger1: redDark.red1,
    danger2: redDark.red2,
  },
  breakpoints: {
    tablet: '768px',
    mobile: '425px',
  },
}
