import {
  slate,
  slateDark,
  blue,
  blueDark,
  red,
  redDark,
  green,
  greenDark,
  yellow,
  yellowDark,
} from '@radix-ui/colors'

export type CustomTheme = typeof lightTheme

export const lightTheme = {
  type: 'light',
  colors: {
    gray1: slate.slate1,
    gray2: slate.slate2,
    gray3: slate.slate3,
    gray4: slate.slate4,
    gray5: slate.slate5,
    gray6: slate.slate6,
    gray7: slate.slate7,
    gray8: slate.slate8,
    gray9: slate.slate9,
    gray10: slate.slate10,
    gray11: slate.slate11,
    gray12: slate.slate12,
    accentBase: blue.blue1,
    accentBgSubtle: blue.blue2,
    accentBg: blue.blue3,
    accentBgHover: blue.blue4,
    accentBgActive: blue.blue5,
    accentLine: blue.blue6,
    accentBorder: blue.blue7,
    accentBorderHover: blue.blue8,
    accentSolid: blue.blue9,
    accentSolidHover: blue.blue10,
    accentText: blue.blue11,
    accentTextContrast: blue.blue12,
    success1: green.green1,
    success2: green.green2,
    warning1: yellow.yellow1,
    warning2: yellow.yellow2,
    danger1: red.red1,
    danger2: red.red2,
  },
  breakpoints: {
    tablet: '768px',
    mobile: '425px',
  },
}

export const darkTheme = {
  type: 'dark',
  colors: {
    gray1: slateDark.slate1,
    gray2: slateDark.slate2,
    gray3: slateDark.slate3,
    gray4: slateDark.slate4,
    gray5: slateDark.slate5,
    gray6: slateDark.slate6,
    gray7: slateDark.slate7,
    gray8: slateDark.slate8,
    gray9: slateDark.slate9,
    gray10: slateDark.slate10,
    gray11: slateDark.slate11,
    gray12: slateDark.slate12,
    accentBase: blueDark.blue1,
    accentBgSubtle: blueDark.blue2,
    accentBg: blueDark.blue3,
    accentBgHover: blueDark.blue4,
    accentBgActive: blueDark.blue5,
    accentLine: blueDark.blue6,
    accentBorder: blueDark.blue7,
    accentBorderHover: blueDark.blue8,
    accentSolid: blueDark.blue9,
    accentSolidHover: blueDark.blue10,
    accentText: blueDark.blue11,
    accentTextContrast: blueDark.blue12,
    success1: greenDark.green1,
    success2: greenDark.green2,
    warning1: yellowDark.yellow1,
    warning2: yellowDark.yellow2,
    danger1: redDark.red1,
    danger2: redDark.red2,
  },
  breakpoints: {
    tablet: '768px',
    mobile: '425px',
  },
}
