import {
  mauve,
  mauveDark,
  violet,
  violetDark,
  red,
  redDark,
  green,
  greenDark,
  yellow,
  yellowDark,
} from '@radix-ui/colors'

export type CustomTheme = typeof lightTheme

export const lightTheme = {
  type: 'light',
  colors: {
    gray1: mauve.mauve1,
    gray2: mauve.mauve2,
    gray3: mauve.mauve3,
    gray4: mauve.mauve4,
    gray5: mauve.mauve5,
    gray6: mauve.mauve6,
    gray7: mauve.mauve7,
    gray8: mauve.mauve8,
    gray9: mauve.mauve9,
    gray10: mauve.mauve10,
    gray11: mauve.mauve11,
    gray12: mauve.mauve12,
    accentBase: violet.violet1,
    accentBgSubtle: violet.violet2,
    accentBg: violet.violet3,
    accentBgHover: violet.violet4,
    accentBgActive: violet.violet5,
    accentLine: violet.violet6,
    accentBorder: violet.violet7,
    accentBorderHover: violet.violet8,
    accentSolid: violet.violet9,
    accentSolidHover: violet.violet10,
    accentText: violet.violet11,
    accentTextContrast: violet.violet12,
    success1: green.green1,
    success2: green.green2,
    warning1: yellow.yellow1,
    warning2: yellow.yellow2,
    danger1: red.red1,
    danger2: red.red2,
  },
}

export const darkTheme = {
  type: 'dark',
  colors: {
    gray1: mauveDark.mauve1,
    gray2: mauveDark.mauve2,
    gray3: mauveDark.mauve3,
    gray4: mauveDark.mauve4,
    gray5: mauveDark.mauve5,
    gray6: mauveDark.mauve6,
    gray7: mauveDark.mauve7,
    gray8: mauveDark.mauve8,
    gray9: mauveDark.mauve9,
    gray10: mauveDark.mauve10,
    gray11: mauveDark.mauve11,
    gray12: mauveDark.mauve12,
    accentBase: violetDark.violet1,
    accentBgSubtle: violetDark.violet2,
    accentBg: violetDark.violet3,
    accentBgHover: violetDark.violet4,
    accentBgActive: violetDark.violet5,
    accentLine: violetDark.violet6,
    accentBorder: violetDark.violet7,
    accentBorderHover: violetDark.violet8,
    accentSolid: violetDark.violet9,
    accentSolidHover: violetDark.violet10,
    accentText: violetDark.violet11,
    accentTextContrast: violetDark.violet12,
    success1: greenDark.green1,
    success2: greenDark.green2,
    warning1: yellowDark.yellow1,
    warning2: yellowDark.yellow2,
    danger1: redDark.red1,
    danger2: redDark.red2,
  },
}
